providers = ["python"]

[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --noinput"]

[start]
cmd = "cd backend && gunicorn backend.wsgi --bind 0.0.0.0:$PORT"
