[build]
builder = "NIXPACKS"

[deploy]
releaseCommand = "cd backend && python manage.py migrate --noinput"
startCommand = "cd backend && gunicorn backend.wsgi --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
