# Generated by Django 5.1.5 on 2026-07-16 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='target_audience',
            field=models.ManyToManyField(blank=True, related_name='targeted_ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AIEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept_score', models.IntegerField()),
                ('feasibility_score', models.IntegerField()),
                ('application_score', models.IntegerField()),
                ('overall_notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation', to='core.idea')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numeric_score', models.IntegerField()),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.idea')),
            ],
        ),
    ]
