# Generated by Django 5.1.5 on 2026-07-18 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_company_name_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='idea_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.idea')),
            ],
        ),
    ]
